# Generated by Django 5.1.1 on 2024-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeastrologique',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='themeastrologique',
            name='heure_naissance',
        ),
        migrations.RemoveField(
            model_name='themeastrologique',
            name='nom_du_theme',
        ),
        migrations.RemoveField(
            model_name='themeastrologique',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='themeastrologique',
            name='ville',
        ),
        migrations.AddField(
            model_name='themeastrologique',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themeastrologique',
            name='birthtime',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themeastrologique',
            name='city_of_birth',
            field=models.CharField(default='Non défini', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themeastrologique',
            name='country_of_birth',
            field=models.CharField(default='Non défini', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themeastrologique',
            name='name',
            field=models.CharField(default='Thème par défaut', max_length=255),
            preserve_default=False,
        ),
    ]
